# Generated by Django 5.1.15 on 2026-01-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cycle",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Общий"),
                    ("BASIC", "Базовый"),
                    ("ACCELERATED", "Ускоренный"),
                    ("EXTRA", "Дополнительный"),
                ],
                default="GENERAL",
                max_length=16,
            ),
        ),
    ]
