# Generated by Django 5.1.15 on 2026-01-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_cycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="school_grade",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
