# Generated by Django 5.1.15 on 2026-03-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_profile_cycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cycle",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Общий"),
                    ("BASIC", "Базовый"),
                    ("ACCELERATED", "Специальный"),
                    ("EXTRA", "Дополнительный"),
                ],
                default="GENERAL",
                max_length=16,
            ),
        ),
    ]
