services:
  web:
    volumes:
      - .:/home/sysuser/music-Gradebook
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SQLITE_PATH: /home/sysuser/music-Gradebook/db.sqlite3
      DJANGO_SEED_DEMO: "1"
