# Generated by Django 5.1.15 on 2026-01-21 11:39

import django.db.models.deletion
from django.db import migrations, models


def forwards_create_course_types(apps, schema_editor):
    Course = apps.get_model("school", "Course")
    CourseType = apps.get_model("school", "CourseType")
    for course in Course.objects.all():
        if not course.course_type:
            continue
        course_type, _ = CourseType.objects.get_or_create(name=course.course_type)
        course.course_type_new = course_type
        course.save(update_fields=["course_type_new"])



class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="course",
            name="course_type_new",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses_new",
                to="school.coursetype",
            ),
        ),
        migrations.RunPython(forwards_create_course_types, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="course",
            name="course_type",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="course_type_new",
            new_name="course_type",
        ),
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="school.coursetype",
            ),
        ),
    ]
