# Generated by Django 5.1.15 on 2026-01-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
