# Generated by Django 5.1.15 on 2026-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_event_external_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("LESSON", "Урок"),
                    ("EXAM", "Экзамен"),
                    ("CONCERT", "Концерт"),
                    ("QUIZ", "Квиз"),
                    ("CONTROL", "Контрольная работа"),
                    ("FINAL", "Итоговая оценка"),
                    ("MILESTONE", "Промежуточная проверка"),
                ],
                max_length=16,
            ),
        ),
    ]
