# Generated by Django 5.1.15 on 2026-01-09 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0002_rename_assignmentstatus_to_assignmenttarget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmenttarget",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="homework.assignment",
            ),
        ),
        migrations.AlterField(
            model_name="assignmenttarget",
            name="status",
            field=models.CharField(
                choices=[("TODO", "TODO"), ("DONE", "DONE")],
                default="TODO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="assignmenttarget",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_targets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
