# Generated by Django 5.1.15 on 2026-02-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0003_alter_assignmenttarget_assignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="assignments/"),
        ),
    ]
