# Generated by Django 5.1.15 on 2026-01-21 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_create_lesson_students(apps, schema_editor):
    Lesson = apps.get_model("lessons", "Lesson")
    LessonStudent = apps.get_model("lessons", "LessonStudent")
    Enrollment = apps.get_model("school", "Enrollment")
    for lesson in Lesson.objects.all():
        student_ids = Enrollment.objects.filter(course_id=lesson.course_id).values_list("student_id", flat=True)
        LessonStudent.objects.bulk_create(
            [LessonStudent(lesson_id=lesson.id, student_id=student_id, attended=True) for student_id in student_ids],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
        ("school", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attended", models.BooleanField(default=True)),
                ("result", models.TextField(blank=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_entries",
                        to="lessons.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("lesson", "student")},
            },
        ),
        migrations.RunPython(forwards_create_lesson_students, migrations.RunPython.noop),
    ]
