# Generated by Django 5.1.15 on 2026-02-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_lessonstudent"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="lessons/"),
        ),
    ]
