# Generated by Django 5.1.15 on 2026-01-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_lesson_cycle_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
