# Generated by Django 5.1.15 on 2026-02-24 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_lesson_attachment"),
        ("school", "0002_coursetype_alter_course_course_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ]
                    ),
                ),
                (
                    "lesson_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("start_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=45)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_schedules",
                        to="school.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("weekday", "start_time", "id"),
                "unique_together": {("teacher", "student", "weekday", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="LessonSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=45)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Запланирован"),
                            ("DONE", "Проведен"),
                            ("MISSED", "Пропущен"),
                        ],
                        default="PLANNED",
                        max_length=16,
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Присутствовал"),
                            ("ABSENT", "Отсутствовал"),
                            ("SICK", "Болел"),
                            ("LATE", "Опоздал"),
                        ],
                        default="PRESENT",
                        max_length=16,
                    ),
                ),
                (
                    "result_note",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("report_comment", models.TextField(blank=True, default="")),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_slots",
                        to="school.course",
                    ),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slot",
                        to="lessons.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_lesson_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slots",
                        to="lessons.studentschedule",
                    ),
                ),
            ],
            options={
                "ordering": ("scheduled_date", "start_time", "id"),
                "unique_together": {
                    ("teacher", "student", "scheduled_date", "start_time")
                },
            },
        ),
    ]
