# Generated by Django 5.1.15 on 2026-03-11 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_studentschedule_lessonslot"),
        ("school", "0002_coursetype_alter_course_course_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonslot",
            options={
                "ordering": ("scheduled_date", "start_time", "id"),
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
        migrations.AlterModelOptions(
            name="studentschedule",
            options={
                "ordering": ("weekday", "start_time", "id"),
                "verbose_name": "регулярный урок",
                "verbose_name_plural": "регулярные уроки",
            },
        ),
        migrations.AddField(
            model_name="lessonslot",
            name="reschedule_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="lessonslot",
            name="rescheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonslot",
            name="rescheduled_from_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonslot",
            name="rescheduled_from_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="lessonslot",
            index=models.Index(
                fields=["schedule", "rescheduled_from_date", "rescheduled_from_time"],
                name="lessonslot_resch_src_idx",
            ),
        ),
    ]
